### ISSUE TITLE
国产iot操作系统中，alios的文档做的是最差的，没有之一。

### ISSUE THREAD

**Issue by chenyang8094** [alibaba/AliOS-Things#31]

**Comment by NEXTLEO** [comment]
应改刚刚起步。

**Comment by hanfengcan** [comment]
刚起步，资料可能是逐渐完善的，话说得那么难听。你是友商派来的吗？

**Comment by theblusky8888** [comment]
有问题就反馈，也不错。

**Comment by mqlinks** [comment]
阿里加油！

**Comment by zjh6607476** [comment]
文档确实不够详细，要加油呀！

**Comment by librae8226** [comment]
github wiki 上的文档脉络已经过一轮整理
https://github.com/alibaba/AliOS-Things/wiki
感谢提出宝贵意见

**Comment by iChenwin** [comment]
国产iot操作系统还有哪些呢？ @chenyang8094

**Comment by HankFan** [comment]
庆科的mico 华为的lite os



发自我的小米手机在 Wayne Chen <notifications@github.com>，2018年3月22日 14:00写道：国产iot操作系统还有哪些呢？ @chenyang8094

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alibaba/AliOS-Things","title":"alibaba/AliOS-Things","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alibaba/AliOS-Things"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iChenwin in #31: 国产iot操作系统还有哪些呢？ @chenyang8094 "}],"action":{"name":"View Issue","url":"https://github.com/alibaba/AliOS-Things/issues/31#issuecomment-375189405"}}}

**Comment by lzpfmh** [comment]
@chenyang8094 能分享国产其他IoT系统文档清楚点的，系统功能全面的，也学习下。谢谢哦。
